### ISSUE TITLE
should not designate one node as master

### ISSUE THREAD

**Issue by maxadamo** [fraenki/puppet-galera#116]
Hi Frank. 

there is no concept of "master" that can be pre-assigned, and that can always be used to bootstrap the cluster. 
There is one node in the cluster which can be considered safe to bootstrap. This node is the last node that was alive in the cluster and it can be determined by grepping as following: 
```
grep safe_to_bootstrap ~mysql/grastate.dat 
safe_to_bootstrap: 0
```

If it's `1` you can bootstrap from that node. 
Of course you can bootstrap for whatever node, but the risk of loosing data is *considerably high*, depending how long the last node was alive, while the other nodes were down!!

For you reference: [Galera Safe To Bootstrap](http://galeracluster.com/2016/11/introducing-the-safe-to-bootstrap-feature-in-galera-cluster/)

Hope it helps!

**Comment by fraenki** [comment]
@maxadamo Thanks! I'm aware of this issue. From a historical standpoint I _guess_ this feature exists in this module to make it possible to bootstrap a _new_ cluster.

I take your report as an opportunity to think about how this feature could be improved for _existing_ clusters.

**Comment by maxadamo** [comment]
I can understand.... tbh, I was investigating you  modules, since it's not easy to find a proper solution. 
I have my own tool, and my own module [galera_proxysql](https://forge.puppet.com/maxadamo/galera_proxysql)

but I'm using a puppet exec, with my wrapper with the following command:
```
command => 'galera_wizard.py -bn -f || galera_wizard.py -jn -f',
```
which means: try to bootstrap or try to join. 
I do also have a fact, checking the status on the port 9200.

**Comment by maxadamo** [comment]
There is a possibility to use PuppetDB. I have seen it in some other module. But while it's possible to store some information information on there it's still not easy to combine together all the moving parts. 
Let's see where we get :)

**Comment by ThoTischner** [comment]
Maybe this approach could be extended to support also this type of scenario: https://github.com/fraenki/puppet-galera/issues/118#issuecomment-560414500

**Comment by fraenki** [comment]
I was considering using `grastate.dat` in order to not bootstrap from the wrong node. However, this would require to know the location of `datadir`, but this is either set by puppetlabs/mysql or by a custom config. So there's no reliable way to determine the `datadir` and hence no way to query `grastate.dat`.

So I've decided to abandon this idea for now. In my experience the current mode of operation has not caused any issues in ~5 years. If someone wants to play it extra safe it would always be possible to set `bootstrap_command` to something like `/bin/false`.

I'm going to close this issue now. If someone has a solution to the formentioned problem or has a better idea, please let me know (or better: submit a pull request :)).
