### ISSUE TITLE
Doubt over Debian workaround

### ISSUE THREAD

**Issue by Rocco83** [fraenki/puppet-galera#161]
Hi,

First of all, thanks for your work.
It's an amazing module.

I have a doubt over the galera::debian manifest anyway.

According to the comment https://github.com/fraenki/puppet-galera/blob/master/manifests/debian.pp#L5, i would understand that the workaround should run once, while the galera package is not installed.

But, the whole code start everytime, as https://github.com/fraenki/puppet-galera/blob/master/manifests/debian.pp#L12 does not have any dependecy, and when it reach https://github.com/fraenki/puppet-galera/blob/master/manifests/debian.pp#L39 the tmpdir is deleted.

What i'm wondering, is if this code should run only if galera is *not* installed (which can be done, in example, via dpkg check).

I'm sure I'm missing some piece of the puzzle, so... any comment would be welcome :)

Thank you very much,
Daniele

**Comment by fraenki** [comment]
@Rocco83 Thanks for the report. Did you run into _actual_ problems or are you just curious? :)

I agree with your observation. This workaround should probably only run on _new_ galera nodes. However, if the package/config was changed then it _may_ be necessary to run these workarounds again (because Debian systems tend to do strange things on package installation/update).

It would help me to understand the impact if you could provide the output of a Puppet run on a galera node that is fully functional and does not need any configuration/package changes.

**Comment by fraenki** [comment]
Almost 2 years have passed and no problem was reported, so closing this now...
